#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : azure-cosmos
Version  : 4.2.0
Release  : 10
URL      : https://files.pythonhosted.org/packages/87/0d/ee9d2110b82692af77b2ff22294a5563948b42d25f92a5df95471612dbd8/azure-cosmos-4.2.0.zip
Source0  : https://files.pythonhosted.org/packages/87/0d/ee9d2110b82692af77b2ff22294a5563948b42d25f92a5df95471612dbd8/azure-cosmos-4.2.0.zip
Summary  : Microsoft Azure Cosmos Client Library for Python
Group    : Development/Tools
License  : MIT
Requires: azure-cosmos-license = %{version}-%{release}
Requires: azure-cosmos-python = %{version}-%{release}
Requires: azure-cosmos-python3 = %{version}-%{release}
Requires: azure-core
Requires: azure-nspkg
Requires: six
BuildRequires : azure-core
BuildRequires : azure-nspkg
BuildRequires : buildreq-distutils3
BuildRequires : six

%description
Azure Cosmos DB is a globally distributed, multi-model database service that supports document, key-value, wide-column, and graph databases.
        
        Use the Azure Cosmos DB SQL API SDK for Python to manage databases and the JSON documents they contain in this NoSQL database service.
        
        * Create Cosmos DB **databases** and modify their settings
        * Create and modify **containers** to store collections of JSON documents
        * Create, read, update, and delete the **items** (JSON documents) in your containers
        * Query the documents in your database using **SQL-like syntax**
        
        [SDK source code][source_code] | [Package (PyPI)][cosmos_pypi] | [API reference documentation][ref_cosmos_sdk] | [Product documentation][cosmos_docs] | [Samples][cosmos_samples]

%package license
Summary: license components for the azure-cosmos package.
Group: Default

%description license
license components for the azure-cosmos package.


%package python
Summary: python components for the azure-cosmos package.
Group: Default
Requires: azure-cosmos-python3 = %{version}-%{release}

%description python
python components for the azure-cosmos package.


%package python3
Summary: python3 components for the azure-cosmos package.
Group: Default
Requires: python3-core
Provides: pypi(azure_cosmos)
Requires: pypi(azure_core)
Requires: pypi(six)

%description python3
python3 components for the azure-cosmos package.


%prep
%setup -q -n azure-cosmos-4.2.0
cd %{_builddir}/azure-cosmos-4.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1607992927
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/azure-cosmos
cp %{_builddir}/azure-cosmos-4.2.0/LICENSE.txt %{buildroot}/usr/share/package-licenses/azure-cosmos/524b3e104ccaa2e8948a7211d132bea8ca43d80f
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## Remove excluded files
rm -f %{buildroot}/usr/lib/python3.8/site-packages/azure/__init__.py
rm -f %{buildroot}/usr/lib/python3.8/site-packages/azure/__pycache__/__init__.cpython-38.pyc

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/azure-cosmos/524b3e104ccaa2e8948a7211d132bea8ca43d80f

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
